### ISSUE TITLE
Consider setting up greenkeeper?

### ISSUE THREAD

**Issue by magicmark** [Yelp/lemon-reset#17]
https://greenkeeper.io/

**Comment by magicmark** [comment]
@tomelm could you grant greenkeeper access to this repo? thanks!

**Comment by magicmark** [comment]
@tomelm ping!

**Comment by tomelm** [comment]
@magicmark we're looking into this internally, will ping you on the ticket.

**Comment by mxmul** [comment]
Fixed by #31!
